urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import DetailView, ListView, TemplateView
from jpparse.models import Class, Method
from jpparse.views import ClassListView
from django.views.decorators.cache import cache_page
urlpatterns = patterns('jpparse.views',
	url(r'^$', ClassListView.as_view(), name="main"),
	url(r'^info/$', TemplateView.as_view(template_name="jpparse/info.html"), name="info"),
	url(r'^classes/search/$', 'searchview'),
	url(r'^classes/$', ClassListView.as_view(), name="class_list_view"),
#	url(r'^classes/(?P<rpp>\d+)/$', ClassListView.as_view(), name="class_rpp_list_view"),
#	url(r'^classes/$', cache_page(ClassListView.as_view(), 60*10), name="class_list_view"),
	url(r'^class/(?P<pk>\d+)/$', DetailView.as_view(model=Class,), name="class_detail_view"),
	url(r'^method/(?P<pk>\d+)/$', DetailView.as_view(model=Method,), name="method_detail_view"),
)

models.py
from django.db import models
from django.contrib import admin
from django.contrib.auth.models import User


class Method(models.Model):
	name = models.CharField(max_length=5000)
	signature = models.CharField(max_length=400)
	def __unicode__(self):
		return self.name
class Class(models.Model):
	name = models.CharField(max_length=5000)
	methods = models.ManyToManyField(Method, blank=True, null=True)
	def __unicode__(self):
		return self.name
class Variable(models.Model):
	name = models.CharField(max_length=400)
	signature = models.CharField(max_length=400)
	method = models.ForeignKey(Method)
	def __unicode__(self):
		return self.name
class GlobalVariable(models.Model):
	name = models.CharField(max_length=400)
	signature = models.CharField(max_length=400)
	classowner = models.ForeignKey(Class)
	def __unicode__(self):
		return self.name
class CodeSegment(models.Model):
	stack = models.IntegerField()
	local = models.IntegerField()
	args_size = models.IntegerField()
	length = models.IntegerField()
	method = models.ForeignKey(Method)

class MethodAdmin(admin.ModelAdmin):
	search_fields = ["name"]
class ClassAdmin(admin.ModelAdmin):
	search_fields = ["name"]
class VariableAdmin(admin.ModelAdmin):
	search_fields = ["name"]
class GlobalVariableAdmin(admin.ModelAdmin):
	search_fields = ["name"]
class CodeSegmentAdmin(admin.ModelAdmin):
	search_fields = ["method"]

views.py
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.views.generic import ListView, DetailView, TemplateView
from jpparse.models import Class, Method
from django.views.decorators.cache import cache_page
from django.db.models import Q
class ClassListView(ListView):
	model = Class
	results_per_page = 50
	paginate_by = results_per_page
	context_object_name = "class_list"
	
def searchview(request):
	query = request.GET.get('q', '')
	if query:
		qset = (Q(name__iregex=query))
		results = Class.objects.filter(qset)
	else:
		results = []

	p = dict(results=results, query=query)
	return render_to_response("jpparse/class_search.html",p, RequestContext(request))		

templates/jpparse/class_detail.html
{% extends "jpparse/index.html" %}

{% block content %}
<h3>Class: {{class.name}}</h3>
<table class="table table-striped">
	<thead>
	<tr>
		<th>Methods</th>
	</tr>
	</thead>
	<tbody>
		<tr>
			<td>{% for method in class.methods.all %}
                                <li><a href="{% url method_detail_view method.id %}">{{method.name}}</a></li>
                        {%endfor%}</td>
		</tr>
	</tbody>
</table>
<table class="table table-striped">
	<thead>
	<tr>
		<th>Global Variable</th>
		<th>Signature</th>
	</tr>
	</thead>
	<tbody>
		{% for variable in class.globalvariable_set.all %}
		<tr>
			<td>{{variable.name}}</td>
			<td>{{variable.signature}}</td>
		</tr>
		{% endfor %}
	</tbody>
</table>
{% endblock %}

templates/jpparse/class_list.html
{% extends "jpparse/index.html" %}

{% block content %}
<h1>Class Listing</h1>
<br/>
<form action="{% url class_list_search %}" method="GET" class="well form-search">
	<input type="text" name="q" class="input-xxlarge search-query">
	<input type="submit" value="Search" class="btn">
</form>
<table class="table table-striped">
	<thead>
	<tr>
		<th>Class Name</th>
<!--		<th>Methods</th> -->
	</tr>
	</thead>
	<tbody>
	{% for class in class_list %}
		<tr>
			<td><a href="{% url class_detail_view class.id %}">{{class.name}}</a></td>
<!--			<td><ul>
			{% for method in class.methods.all %}
				<li><a href="{% url method_detail_view method.id %}">{{method.name}}</a></li>
			{%endfor%} 
			</ul></td> -->
		</tr>
	{% endfor %}
	</tbody>
</table>
{% if is_paginated %}
    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ page_obj.number }} of {{ paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
            {% endif %}
        </span>
    </div>
{% endif %}

{% endblock %}

templates/jpparse/class_search.html
{% extends "jpparse/index.html" %}

{% block content %}
<h1>Class Listing</h1>
<br/>
<form action="{% url jpparse.views.searchview %}" method="GET" class="well form-search">
	<input type="text" name="q" class="input-xxlarge search-query">
	<input type="submit" value="Search" class="btn">
</form>
{% if query %}
<h3> Results for '{{query|escape}}' </h3>
<table class="table table-striped">
	<thead>
	<tr>
		<th>Class Name</th>
<!--		<th>Methods</th> -->
	</tr>
	</thead>
	<tbody>
	{% for class in results %}
		<tr>
			<td><a href="{% url class_detail_view class.id %}">{{class.name}}</a></td>
<!--			<td><ul>
			{% for method in class.methods.all %}
				<li><a href="{% url method_detail_view method.id %}">{{method.name}}</a></li>
			{%endfor%} 
			</ul></td> -->
		</tr>
	{% endfor %}
	</tbody>
</table>
{% else %}
<p> No Query Given </p>
{% endif %}
{% if is_paginated %}
    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ page_obj.number }} of {{ paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
            {% endif %}
        </span>
    </div>
{% endif %}

{% endblock %}

templates/jpparse/index.html
<!DOCTYPE html>
<html>
  <head>
    <title>jpparse</title>
    <!-- Bootstrap -->
    <link href="{{STATIC_URL}}bootstrap/css/bootstrap.min.css" rel="stylesheet" media="screen">
 
    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
	table {
		table-layout:fixed;
		word-wrap: break-word;
	}
    </style>
  </head>
  <body>
    <script src="http://code.jquery.com/jquery-latest.js"></script>
    <script src="{{STATIC_URL}}bootstrap/js/bootstrap.min.js"></script>
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
		<ul class="nav">
		<li class="active">
			<a class="brand" href="{% url main %}">jpparse</a>
		</li>
		<li><a href="{% url info %}">info</a></li>
		<li><a href="{% url class_list_view %}">browse: classes</a></li>
	</div>
      </div>
    </div>
   <div class="container">
	<div class="row">
	{% block content %}{% endblock %}
	</div>
  </div>
  </body>
</html>

templates/jpparse/info.html
{% extends "jpparse/index.html" %}

{% block content %}
<h1>Information</h1>
{% endblock %}

templates/jpparse/method_detail.html
{% extends "jpparse/index.html" %}

{% block content %}
<h3>Method: {{method.name}}</h3>
{% for class in method.class_set.all %}
<h4>Of Class: {{class.name}}</h4>
{% endfor %}
<table class="table table-striped">
	<thead>
	<tr>
		<th>Signature</th>
	</tr>
	</thead>
	<tbody>
		<tr>
			<td>{{method.signature}}</td>
		</tr>
	</tbody>
</table>
<table class="table table-striped">
	<thead>
	<tr>
		<th>Variable</th>
		<th>Variable Signature</th>
	</tr>
	</thead>
	<tbody>
		{% for variable in method.variable_set.all %}
		<tr>
			<td> {{variable.name}}</td>
			<td>{{variable.signature}}</td>
		</tr>
		{% endfor %}
	</tbody>
</table>
<table class="table table-striped">
	<thead>
	<tr>
		<th>Stack</th>
		<th>Local</th>
		<th>Args_Size</th>
		<th>Length</th>
	</tr>
	</thead>
	<tbody>
		{% for code in method.codesegment_set.all %}
		<tr>
			<td> {{code.stack}}</td>
			<td>{{code.local}}</td>
			<td>{{code.args_size}}</td>
			<td>{{code.length}}</td>
		</tr>
		{% endfor %}
	</tbody>
</table>
{% endblock %}